public enum MenuSelectionEnum {
    FIRST_OPTION_SELECTED,
    SECOND_OPTION_SELECTED,
    THIRD_OPTION_SELECTED,
    FOURTH_OPTION_SELECTED,
    FIFTH_OPTION_SELECTED,
    SIXTH_OPTION_SELECTED,
    INVALID_SELECTION;
}
